# Generated by Django 4.1 on 2022-11-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "Users Profiles",
            },
        ),
        migrations.RenameField(
            model_name="userprofile", old_name="avater", new_name="avatar",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="title",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
